//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match..
        /// </summary>
        internal static string AwardmentFirstMatchWonDescription {
            get {
                return ResourceManager.GetString("AwardmentFirstMatchWonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string AwardmentFirstMatchWonName {
            get {
                return ResourceManager.GetString("AwardmentFirstMatchWonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a territory..
        /// </summary>
        internal static string AwardmentFirstTerritoryCapturedDescription {
            get {
                return ResourceManager.GetString("AwardmentFirstTerritoryCapturedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First!.
        /// </summary>
        internal static string AwardmentFirstTerritoryCapturedName {
            get {
                return ResourceManager.GetString("AwardmentFirstTerritoryCapturedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstoppable.
        /// </summary>
        internal static string AwardmentLongStreakDescription {
            get {
                return ResourceManager.GetString("AwardmentLongStreakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 20 matches in a row..
        /// </summary>
        internal static string AwardmentLongStreakName {
            get {
                return ResourceManager.GetString("AwardmentLongStreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play 100 matches..
        /// </summary>
        internal static string AwardmentManyMatchesPlayedDescription {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesPlayedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated.
        /// </summary>
        internal static string AwardmentManyMatchesPlayedName {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesPlayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 100 matches..
        /// </summary>
        internal static string AwardmentManyMatchesWonDescription {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesWonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic Win.
        /// </summary>
        internal static string AwardmentManyMatchesWonName {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesWonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture 1000 territories..
        /// </summary>
        internal static string AwardmentManyTerritoriesCapturedDescription {
            get {
                return ResourceManager.GetString("AwardmentManyTerritoriesCapturedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conqueror.
        /// </summary>
        internal static string AwardmentManyTerritoriesCapturedName {
            get {
                return ResourceManager.GetString("AwardmentManyTerritoriesCapturedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match in under 3 minutes..
        /// </summary>
        internal static string AwardmentQuickWinDescription {
            get {
                return ResourceManager.GetString("AwardmentQuickWinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly.
        /// </summary>
        internal static string AwardmentQuickWinName {
            get {
                return ResourceManager.GetString("AwardmentQuickWinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 3 matches in a row..
        /// </summary>
        internal static string AwardmentShortStreakDescription {
            get {
                return ResourceManager.GetString("AwardmentShortStreakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Trick.
        /// </summary>
        internal static string AwardmentShortStreakName {
            get {
                return ResourceManager.GetString("AwardmentShortStreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match in under a minute..
        /// </summary>
        internal static string AwardmentVeryQuickWinDescription {
            get {
                return ResourceManager.GetString("AwardmentVeryQuickWinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitz.
        /// </summary>
        internal static string AwardmentVeryQuickWinName {
            get {
                return ResourceManager.GetString("AwardmentVeryQuickWinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer A.
        /// </summary>
        internal static string ComputerA {
            get {
                return ResourceManager.GetString("ComputerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer B.
        /// </summary>
        internal static string ComputerB {
            get {
                return ResourceManager.GetString("ComputerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer C.
        /// </summary>
        internal static string ComputerC {
            get {
                return ResourceManager.GetString("ComputerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer D.
        /// </summary>
        internal static string ComputerD {
            get {
                return ResourceManager.GetString("ComputerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string ExceptionException {
            get {
                return ResourceManager.GetString("ExceptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Back to Exit..
        /// </summary>
        internal static string ExceptionExitPrompt {
            get {
                return ResourceManager.GetString("ExceptionExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION DETAILS.
        /// </summary>
        internal static string ExceptionHeader {
            get {
                return ResourceManager.GetString("ExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game experienced an unexpected error and had to end..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Error Details.
        /// </summary>
        internal static string ExceptionMessageDebug {
            get {
                return ResourceManager.GetString("ExceptionMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string ExceptionMessageExit {
            get {
                return ResourceManager.GetString("ExceptionMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string ExceptionMessageTitle {
            get {
                return ResourceManager.GetString("ExceptionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: {0}.
        /// </summary>
        internal static string ExceptionTrace {
            get {
                return ResourceManager.GetString("ExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} won!.
        /// </summary>
        internal static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attacks or moves.
        /// </summary>
        internal static string InstructionsAction {
            get {
                return ResourceManager.GetString("InstructionsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puts pieces down.
        /// </summary>
        internal static string InstructionsCancel {
            get {
                return ResourceManager.GetString("InstructionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selects territories to act on.
        /// </summary>
        internal static string InstructionsMovement {
            get {
                return ResourceManager.GetString("InstructionsMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places new pieces.
        /// </summary>
        internal static string InstructionsPlacement {
            get {
                return ResourceManager.GetString("InstructionsPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picks up pieces to move or attack with.
        /// </summary>
        internal static string InstructionsSelection {
            get {
                return ResourceManager.GetString("InstructionsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owning more territories creates new pieces faster.
        /// </summary>
        internal static string InstructionsTerritories {
            get {
                return ResourceManager.GetString("InstructionsTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces can only move/attack once every 6 seconds.
        /// </summary>
        internal static string InstructionsWaiting {
            get {
                return ResourceManager.GetString("InstructionsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while accessing the network..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept invite..
        /// </summary>
        internal static string NetworkErrorAcceptInvite {
            get {
                return ResourceManager.GetString("NetworkErrorAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signed in gamer cannot play online..
        /// </summary>
        internal static string NetworkErrorCannotPlayOnline {
            get {
                return ResourceManager.GetString("NetworkErrorCannotPlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the match..
        /// </summary>
        internal static string NetworkErrorDisconnected {
            get {
                return ResourceManager.GetString("NetworkErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host ended the match..
        /// </summary>
        internal static string NetworkErrorHostEndedSession {
            get {
                return ResourceManager.GetString("NetworkErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host removed you from the match..
        /// </summary>
        internal static string NetworkErrorRemovedByHost {
            get {
                return ResourceManager.GetString("NetworkErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PurchaseFailedButton {
            get {
                return ResourceManager.GetString("PurchaseFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in, or you cannot purchase content..
        /// </summary>
        internal static string PurchaseFailedText {
            get {
                return ResourceManager.GetString("PurchaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Purchase.
        /// </summary>
        internal static string PurchaseFailedTitle {
            get {
                return ResourceManager.GetString("PurchaseFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player signed out. Returning to the title screen..
        /// </summary>
        internal static string SignedOutError {
            get {
                return ResourceManager.GetString("SignedOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No storage device selected. Continue without saving?.
        /// </summary>
        internal static string StoragePromptReselectCancelled {
            get {
                return ResourceManager.GetString("StoragePromptReselectCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected storage device has been removed. Continue without saving?.
        /// </summary>
        internal static string StoragePromptReselectDisconnected {
            get {
                return ResourceManager.GetString("StoragePromptReselectDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string StoragePromptReselectNo {
            get {
                return ResourceManager.GetString("StoragePromptReselectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reselect Storage Device?.
        /// </summary>
        internal static string StoragePromptReselectTitle {
            get {
                return ResourceManager.GetString("StoragePromptReselectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string StoragePromptReselectYes {
            get {
                return ResourceManager.GetString("StoragePromptReselectYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
    }
}
