//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer A.
        /// </summary>
        internal static string ComputerA {
            get {
                return ResourceManager.GetString("ComputerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer B.
        /// </summary>
        internal static string ComputerB {
            get {
                return ResourceManager.GetString("ComputerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer C.
        /// </summary>
        internal static string ComputerC {
            get {
                return ResourceManager.GetString("ComputerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer D.
        /// </summary>
        internal static string ComputerD {
            get {
                return ResourceManager.GetString("ComputerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string ExceptionException {
            get {
                return ResourceManager.GetString("ExceptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Back to Exit..
        /// </summary>
        internal static string ExceptionExitPrompt {
            get {
                return ResourceManager.GetString("ExceptionExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION DETAILS.
        /// </summary>
        internal static string ExceptionHeader {
            get {
                return ResourceManager.GetString("ExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game experienced an unexpected error and had to end..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Error Details.
        /// </summary>
        internal static string ExceptionMessageDebug {
            get {
                return ResourceManager.GetString("ExceptionMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string ExceptionMessageExit {
            get {
                return ResourceManager.GetString("ExceptionMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string ExceptionMessageTitle {
            get {
                return ResourceManager.GetString("ExceptionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: {0}.
        /// </summary>
        internal static string ExceptionTrace {
            get {
                return ResourceManager.GetString("ExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while accessing the network..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept invite..
        /// </summary>
        internal static string NetworkErrorAcceptInvite {
            get {
                return ResourceManager.GetString("NetworkErrorAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the match..
        /// </summary>
        internal static string NetworkErrorDisconnected {
            get {
                return ResourceManager.GetString("NetworkErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host ended the match..
        /// </summary>
        internal static string NetworkErrorHostEndedSession {
            get {
                return ResourceManager.GetString("NetworkErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host removed you from the match..
        /// </summary>
        internal static string NetworkErrorRemovedByHost {
            get {
                return ResourceManager.GetString("NetworkErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PurchaseFailedButton {
            get {
                return ResourceManager.GetString("PurchaseFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in, or you cannot purchase content..
        /// </summary>
        internal static string PurchaseFailedText {
            get {
                return ResourceManager.GetString("PurchaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Purchase.
        /// </summary>
        internal static string PurchaseFailedTitle {
            get {
                return ResourceManager.GetString("PurchaseFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string StrategyGame {
            get {
                return ResourceManager.GetString("StrategyGame", resourceCulture);
            }
        }
    }
}
