//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string AiDifficultyEasy {
            get {
                return ResourceManager.GetString("AiDifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string AiDifficultyHard {
            get {
                return ResourceManager.GetString("AiDifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string AiDifficultyNormal {
            get {
                return ResourceManager.GetString("AiDifficultyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win the match after losing all but one territory..
        /// </summary>
        internal static string AwardmentBrinkDescription {
            get {
                return ResourceManager.GetString("AwardmentBrinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll Be Back.
        /// </summary>
        internal static string AwardmentBrinkName {
            get {
                return ResourceManager.GetString("AwardmentBrinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a match in every map size and game type..
        /// </summary>
        internal static string AwardmentEveryConfigurationDescription {
            get {
                return ResourceManager.GetString("AwardmentEveryConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimenter.
        /// </summary>
        internal static string AwardmentEveryConfigurationName {
            get {
                return ResourceManager.GetString("AwardmentEveryConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match..
        /// </summary>
        internal static string AwardmentFirstMatchWonDescription {
            get {
                return ResourceManager.GetString("AwardmentFirstMatchWonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        internal static string AwardmentFirstMatchWonName {
            get {
                return ResourceManager.GetString("AwardmentFirstMatchWonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a territory..
        /// </summary>
        internal static string AwardmentFirstTerritoryCapturedDescription {
            get {
                return ResourceManager.GetString("AwardmentFirstTerritoryCapturedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First!.
        /// </summary>
        internal static string AwardmentFirstTerritoryCapturedName {
            get {
                return ResourceManager.GetString("AwardmentFirstTerritoryCapturedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 20 matches in a row..
        /// </summary>
        internal static string AwardmentLongStreakDescription {
            get {
                return ResourceManager.GetString("AwardmentLongStreakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstoppable.
        /// </summary>
        internal static string AwardmentLongStreakName {
            get {
                return ResourceManager.GetString("AwardmentLongStreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play 100 matches..
        /// </summary>
        internal static string AwardmentManyMatchesPlayedDescription {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesPlayedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated.
        /// </summary>
        internal static string AwardmentManyMatchesPlayedName {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesPlayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 100 matches..
        /// </summary>
        internal static string AwardmentManyMatchesWonDescription {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesWonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic Win.
        /// </summary>
        internal static string AwardmentManyMatchesWonName {
            get {
                return ResourceManager.GetString("AwardmentManyMatchesWonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place 250 pieces..
        /// </summary>
        internal static string AwardmentManyPiecesPlacedDescription {
            get {
                return ResourceManager.GetString("AwardmentManyPiecesPlacedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string AwardmentManyPiecesPlacedName {
            get {
                return ResourceManager.GetString("AwardmentManyPiecesPlacedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture 1000 territories..
        /// </summary>
        internal static string AwardmentManyTerritoriesCapturedDescription {
            get {
                return ResourceManager.GetString("AwardmentManyTerritoriesCapturedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conqueror.
        /// </summary>
        internal static string AwardmentManyTerritoriesCapturedName {
            get {
                return ResourceManager.GetString("AwardmentManyTerritoriesCapturedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place 5 pieces in under 1 second..
        /// </summary>
        internal static string AwardmentQuickPiecePlacementDescription {
            get {
                return ResourceManager.GetString("AwardmentQuickPiecePlacementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcer.
        /// </summary>
        internal static string AwardmentQuickPiecePlacementName {
            get {
                return ResourceManager.GetString("AwardmentQuickPiecePlacementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture 3 territories in under 3 seconds..
        /// </summary>
        internal static string AwardmentQuickTerritoryCaptureDescription {
            get {
                return ResourceManager.GetString("AwardmentQuickTerritoryCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitzkrieg.
        /// </summary>
        internal static string AwardmentQuickTerritoryCaptureName {
            get {
                return ResourceManager.GetString("AwardmentQuickTerritoryCaptureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match in under 3 minutes..
        /// </summary>
        internal static string AwardmentQuickWinDescription {
            get {
                return ResourceManager.GetString("AwardmentQuickWinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly.
        /// </summary>
        internal static string AwardmentQuickWinName {
            get {
                return ResourceManager.GetString("AwardmentQuickWinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture the same territory 10 times in a single match..
        /// </summary>
        internal static string AwardmentRecaptureDescription {
            get {
                return ResourceManager.GetString("AwardmentRecaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back and Forth.
        /// </summary>
        internal static string AwardmentRecaptureName {
            get {
                return ResourceManager.GetString("AwardmentRecaptureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 3 matches in a row..
        /// </summary>
        internal static string AwardmentShortStreakDescription {
            get {
                return ResourceManager.GetString("AwardmentShortStreakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Trick.
        /// </summary>
        internal static string AwardmentShortStreakName {
            get {
                return ResourceManager.GetString("AwardmentShortStreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awardment: {0}.
        /// </summary>
        internal static string AwardmentTitle {
            get {
                return ResourceManager.GetString("AwardmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place 1000 pieces..
        /// </summary>
        internal static string AwardmentVeryManyPiecesPlacedDescription {
            get {
                return ResourceManager.GetString("AwardmentVeryManyPiecesPlacedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prolific Producer.
        /// </summary>
        internal static string AwardmentVeryManyPiecesPlacedName {
            get {
                return ResourceManager.GetString("AwardmentVeryManyPiecesPlacedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win a match in under a minute..
        /// </summary>
        internal static string AwardmentVeryQuickWinDescription {
            get {
                return ResourceManager.GetString("AwardmentVeryQuickWinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitz.
        /// </summary>
        internal static string AwardmentVeryQuickWinName {
            get {
                return ResourceManager.GetString("AwardmentVeryQuickWinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer A.
        /// </summary>
        internal static string ComputerA {
            get {
                return ResourceManager.GetString("ComputerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer B.
        /// </summary>
        internal static string ComputerB {
            get {
                return ResourceManager.GetString("ComputerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer C.
        /// </summary>
        internal static string ComputerC {
            get {
                return ResourceManager.GetString("ComputerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer D.
        /// </summary>
        internal static string ComputerD {
            get {
                return ResourceManager.GetString("ComputerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Attack/Move.
        /// </summary>
        internal static string ControlsA {
            get {
                return ResourceManager.GetString("ControlsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        internal static string ControlsB {
            get {
                return ResourceManager.GetString("ControlsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory.
        /// </summary>
        internal static string ControlsLStick {
            get {
                return ResourceManager.GetString("ControlsLStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string ControlsStart {
            get {
                return ResourceManager.GetString("ControlsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Piece.
        /// </summary>
        internal static string ControlsX {
            get {
                return ResourceManager.GetString("ControlsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Art.
        /// </summary>
        internal static string CreditsArt {
            get {
                return ResourceManager.GetString("CreditsArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ling Wang.
        /// </summary>
        internal static string CreditsArtList {
            get {
                return ResourceManager.GetString("CreditsArtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and built by Eric Woroshow.
        /// </summary>
        internal static string CreditsMain {
            get {
                return ResourceManager.GetString("CreditsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound &amp; Music.
        /// </summary>
        internal static string CreditsSoundMusic {
            get {
                return ResourceManager.GetString("CreditsSoundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Bura.
        /// </summary>
        internal static string CreditsSoundMusicList {
            get {
                return ResourceManager.GetString("CreditsSoundMusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string ExceptionException {
            get {
                return ResourceManager.GetString("ExceptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Back to Exit..
        /// </summary>
        internal static string ExceptionExitPrompt {
            get {
                return ResourceManager.GetString("ExceptionExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION DETAILS.
        /// </summary>
        internal static string ExceptionHeader {
            get {
                return ResourceManager.GetString("ExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game experienced an unexpected error and had to end..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Error Details.
        /// </summary>
        internal static string ExceptionMessageDebug {
            get {
                return ResourceManager.GetString("ExceptionMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string ExceptionMessageExit {
            get {
                return ResourceManager.GetString("ExceptionMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string ExceptionMessageTitle {
            get {
                return ResourceManager.GetString("ExceptionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: {0}.
        /// </summary>
        internal static string ExceptionTrace {
            get {
                return ResourceManager.GetString("ExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the humans are defeated!.
        /// </summary>
        internal static string GameLost {
            get {
                return ResourceManager.GetString("GameLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} won!.
        /// </summary>
        internal static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tacticolor is a game about *conquest*. The game is played on a *randomly generated map*. Each color gets an equal number of starting *territories* and *pieces*..
        /// </summary>
        internal static string HowToPlay1 {
            get {
                return ResourceManager.GetString("HowToPlay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Expand your territory* by attacking neighboring enemies. A battle&apos;s outcome is determined by a *roll of dice*. Each piece represents one die. The *higher total dice roll wins* the battle (tie goes to the defender)..
        /// </summary>
        internal static string HowToPlay2 {
            get {
                return ResourceManager.GetString("HowToPlay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every few seconds you&apos;ll get a *new piece* to place. The *more territories* you own the *faster* you&apos;ll get new pieces. You can also *move pieces* between territories to reinforce them..
        /// </summary>
        internal static string HowToPlay3 {
            get {
                return ResourceManager.GetString("HowToPlay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces can only *attack or move* every *five seconds*. Pieces can defend any time..
        /// </summary>
        internal static string HowToPlay4 {
            get {
                return ResourceManager.GetString("HowToPlay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attacks or moves.
        /// </summary>
        internal static string InstructionsAction {
            get {
                return ResourceManager.GetString("InstructionsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puts pieces down.
        /// </summary>
        internal static string InstructionsCancel {
            get {
                return ResourceManager.GetString("InstructionsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selects territories.
        /// </summary>
        internal static string InstructionsMovement {
            get {
                return ResourceManager.GetString("InstructionsMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places new pieces.
        /// </summary>
        internal static string InstructionsPlacement {
            get {
                return ResourceManager.GetString("InstructionsPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picks up pieces to move or attack.
        /// </summary>
        internal static string InstructionsSelection {
            get {
                return ResourceManager.GetString("InstructionsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owning more territories creates new pieces faster.
        /// </summary>
        internal static string InstructionsTerritories {
            get {
                return ResourceManager.GetString("InstructionsTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces can only move or attack every 5 seconds.
        /// </summary>
        internal static string InstructionsWaiting {
            get {
                return ResourceManager.GetString("InstructionsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string MapSizeLarge {
            get {
                return ResourceManager.GetString("MapSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string MapSizeNormal {
            get {
                return ResourceManager.GetString("MapSizeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string MapSizeSmall {
            get {
                return ResourceManager.GetString("MapSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string MapSizeTiny {
            get {
                return ResourceManager.GetString("MapSizeTiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        internal static string MapTypeFilled {
            get {
                return ResourceManager.GetString("MapTypeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Rush.
        /// </summary>
        internal static string MapTypeLandRush {
            get {
                return ResourceManager.GetString("MapTypeLandRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string MenuAiDifficulty {
            get {
                return ResourceManager.GetString("MenuAiDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awardments.
        /// </summary>
        internal static string MenuAwardments {
            get {
                return ResourceManager.GetString("MenuAwardments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string MenuContinue {
            get {
                return ResourceManager.GetString("MenuContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string MenuControls {
            get {
                return ResourceManager.GetString("MenuControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Match.
        /// </summary>
        internal static string MenuCreateMatch {
            get {
                return ResourceManager.GetString("MenuCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MenuCredits {
            get {
                return ResourceManager.GetString("MenuCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        internal static string MenuCycle {
            get {
                return ResourceManager.GetString("MenuCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Back to Main Menu.
        /// </summary>
        internal static string MenuExitNo {
            get {
                return ResourceManager.GetString("MenuExitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Exit to Dashboard.
        /// </summary>
        internal static string MenuExitYes {
            get {
                return ResourceManager.GetString("MenuExitYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Options.
        /// </summary>
        internal static string MenuHelpOptions {
            get {
                return ResourceManager.GetString("MenuHelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Play.
        /// </summary>
        internal static string MenuHowToPlay {
            get {
                return ResourceManager.GetString("MenuHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string MenuInstructions {
            get {
                return ResourceManager.GetString("MenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string MenuInvite {
            get {
                return ResourceManager.GetString("MenuInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          to join.
        /// </summary>
        internal static string MenuJoin {
            get {
                return ResourceManager.GetString("MenuJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Match.
        /// </summary>
        internal static string MenuJoinMatch {
            get {
                return ResourceManager.GetString("MenuJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Match.
        /// </summary>
        internal static string MenuLeaveMatch {
            get {
                return ResourceManager.GetString("MenuLeaveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Back to Match Menu.
        /// </summary>
        internal static string MenuLeaveNo {
            get {
                return ResourceManager.GetString("MenuLeaveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Exit to Main Menu.
        /// </summary>
        internal static string MenuLeaveYes {
            get {
                return ResourceManager.GetString("MenuLeaveYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Game.
        /// </summary>
        internal static string MenuLocalGame {
            get {
                return ResourceManager.GetString("MenuLocalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Size.
        /// </summary>
        internal static string MenuMapSize {
            get {
                return ResourceManager.GetString("MenuMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Type.
        /// </summary>
        internal static string MenuMapType {
            get {
                return ResourceManager.GetString("MenuMapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox LIVE Game.
        /// </summary>
        internal static string MenuMultiplayerGame {
            get {
                return ResourceManager.GetString("MenuMultiplayerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot play online as this gamer..
        /// </summary>
        internal static string MenuMultiplayerUnavailable {
            get {
                return ResourceManager.GetString("MenuMultiplayerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MenuMusic {
            get {
                return ResourceManager.GetString("MenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next/Previous.
        /// </summary>
        internal static string MenuNextPrevious {
            get {
                return ResourceManager.GetString("MenuNextPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string MenuOff {
            get {
                return ResourceManager.GetString("MenuOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string MenuOn {
            get {
                return ResourceManager.GetString("MenuOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string MenuPlayerSlot {
            get {
                return ResourceManager.GetString("MenuPlayerSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Host).
        /// </summary>
        internal static string MenuPlayerSlotHost {
            get {
                return ResourceManager.GetString("MenuPlayerSlotHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Full Version.
        /// </summary>
        internal static string MenuPurchase {
            get {
                return ResourceManager.GetString("MenuPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Match.
        /// </summary>
        internal static string MenuReturnMatch {
            get {
                return ResourceManager.GetString("MenuReturnMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string MenuSounds {
            get {
                return ResourceManager.GetString("MenuSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game  .
        /// </summary>
        internal static string MenuStartGame {
            get {
                return ResourceManager.GetString("MenuStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string MenuToggle {
            get {
                return ResourceManager.GetString("MenuToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Ready.
        /// </summary>
        internal static string MenuToggleReady {
            get {
                return ResourceManager.GetString("MenuToggleReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while accessing the network..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept invite..
        /// </summary>
        internal static string NetworkErrorAcceptInvite {
            get {
                return ResourceManager.GetString("NetworkErrorAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signed in gamer cannot play online..
        /// </summary>
        internal static string NetworkErrorCannotPlayOnline {
            get {
                return ResourceManager.GetString("NetworkErrorCannotPlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a match.
        /// </summary>
        internal static string NetworkErrorCreate {
            get {
                return ResourceManager.GetString("NetworkErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the match..
        /// </summary>
        internal static string NetworkErrorDisconnected {
            get {
                return ResourceManager.GetString("NetworkErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host ended the match..
        /// </summary>
        internal static string NetworkErrorHostEndedSession {
            get {
                return ResourceManager.GetString("NetworkErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a match to join..
        /// </summary>
        internal static string NetworkErrorJoin {
            get {
                return ResourceManager.GetString("NetworkErrorJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host removed you from the match..
        /// </summary>
        internal static string NetworkErrorRemovedByHost {
            get {
                return ResourceManager.GetString("NetworkErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PurchaseFailedButton {
            get {
                return ResourceManager.GetString("PurchaseFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in, or you cannot purchase content..
        /// </summary>
        internal static string PurchaseFailedText {
            get {
                return ResourceManager.GetString("PurchaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Purchase.
        /// </summary>
        internal static string PurchaseFailedTitle {
            get {
                return ResourceManager.GetString("PurchaseFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player signed out. Returning to the title screen..
        /// </summary>
        internal static string SignedOutError {
            get {
                return ResourceManager.GetString("SignedOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No storage device selected. Continue without saving?.
        /// </summary>
        internal static string StoragePromptReselectCancelled {
            get {
                return ResourceManager.GetString("StoragePromptReselectCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected storage device has been removed. Continue without saving?.
        /// </summary>
        internal static string StoragePromptReselectDisconnected {
            get {
                return ResourceManager.GetString("StoragePromptReselectDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string StoragePromptReselectNo {
            get {
                return ResourceManager.GetString("StoragePromptReselectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reselect Storage Device?.
        /// </summary>
        internal static string StoragePromptReselectTitle {
            get {
                return ResourceManager.GetString("StoragePromptReselectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string StoragePromptReselectYes {
            get {
                return ResourceManager.GetString("StoragePromptReselectYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tacticolor.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tacticolor to customize your match!.
        /// </summary>
        internal static string TrialMatchConfiguration {
            get {
                return ResourceManager.GetString("TrialMatchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tacticolor to keep playing and finish your conquest!.
        /// </summary>
        internal static string TrialMatchEnd {
            get {
                return ResourceManager.GetString("TrialMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tacticolor to play online!.
        /// </summary>
        internal static string TrialMultiplayer {
            get {
                return ResourceManager.GetString("TrialMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tacticolor to save your Awardments!.
        /// </summary>
        internal static string TrialUpsellAwardments {
            get {
                return ResourceManager.GetString("TrialUpsellAwardments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tacticolor and experience all the fun!.
        /// </summary>
        internal static string TrialUpsellExit {
            get {
                return ResourceManager.GetString("TrialUpsellExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play online!.
        /// </summary>
        internal static string TrialUpsellReason0 {
            get {
                return ResourceManager.GetString("TrialUpsellReason0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn awardments!.
        /// </summary>
        internal static string TrialUpsellReason1 {
            get {
                return ResourceManager.GetString("TrialUpsellReason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More match types!.
        /// </summary>
        internal static string TrialUpsellReason2 {
            get {
                return ResourceManager.GetString("TrialUpsellReason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish matches!.
        /// </summary>
        internal static string TrialUpsellReason3 {
            get {
                return ResourceManager.GetString("TrialUpsellReason3", resourceCulture);
            }
        }
    }
}
